### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by Kalyanimhala** [Link-AGI/AutoAgents#40]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/Link-AGI/AutoAgents/assets/147402107/99f46555-6cb6-4d08-af0f-672bf90989ba)

**Comment by Kalyanimhala** [comment]
@iCGY96  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by gary23ai** [comment]
We have added a Contributors section to our README file to celebrate and recognize the valuable contributions made to this project. Your feedback is invaluable in helping us improve and maintain the spirit of open-source collaboration.
